name: YouTube HLS Downloader with yt-dlp

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  download_hls:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v4

      - name: yt-dlp'yi yükle
        run: pip install yt-dlp

      - name: M3U8 linklerini al
        run: python yt_m3u8_downloader.py

      - name: m3u8 klasörünü oluştur ve taşı
        run: |
          mkdir -p m3u8
          mv *.m3u8 m3u8/ || echo "Taşınacak dosya yok."

      - name: Değişiklikleri commit et ve push yap
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add m3u8/*.m3u8 || true
          git diff --cached --quiet || (git commit -m "Update m3u8 files [skip ci]" && git push)

      - name: Artifacts olarak ekle (isteğe bağlı)
        uses: actions/upload-artifact@v4
        with:
          name: m3u8-dosyaları
          path: m3u8/*.m3u8
